INSERT INTO usuario (nome, cpf, email) VALUES
('Amanda Dias', '123.456.789-00', 'amanda@email.com'),
('João Silva', '111.222.333-44', 'joao@email.com'),
('Mariana Lima', '222.333.444-55', 'mariana.lima@email.com'),
('Carlos Alberto', '333.444.555-66', 'carlos.alberto@email.com'),
('Fernanda Souza', '444.555.666-77', 'fernanda.souza@email.com'),
('Roberto Oliveira', '555.666.777-88', 'roberto.oliveira@email.com'),
('Patrícia Mendes', '666.777.888-99', 'patricia.mendes@email.com'),
('André Rocha', '777.888.999-00', 'andre.rocha@email.com'),
('Juliana Castro', '888.999.000-11', 'juliana.castro@email.com'),
('Lucas Martins', '999.000.111-22', 'lucas.martins@email.com'),
('Gabriela Costa', '000.111.222-33', 'gabriela.costa@email.com'),
('Felipe Araújo', '111.222.333-00', 'felipe.araujo@email.com'),
('Larissa Almeida', '222.333.444-11', 'larissa.almeida@email.com'),
('Marcelo Ribeiro', '333.444.555-22', 'marcelo.ribeiro@email.com'),
('Bianca Fernandes', '444.555.666-33', 'bianca.fernandes@email.com');

INSERT INTO livro (titulo, autor, genero, ano_publicacao, disponivel, usuario_id) VALUES
('O Pequeno Príncipe', 'Dan Brown', 'Drama', 1912, TRUE, 1),
('Dom Casmurro', 'Isabel Allende', 'Infanto-Juvenil', 1919, TRUE, 2),
('1984', 'Jane Austen', 'Ficção Científica', 1951, FALSE, 3),
('Cem Anos de Solidão', 'Stephen King', 'Terror', 1956, TRUE, 4),
('O Alquimista', 'Franz Kafka', 'Realismo Mágico', 1969, FALSE, 5),
('A Culpa é das Estrelas', 'Ray Bradbury', 'Ficção', 1924, FALSE, 6),
('Cidade de Papel', 'Franz Kafka', 'Romance', 1906, TRUE, 7),
('Orgulho e Preconceito', 'J.R.R. Tolkien', 'Terror', 1978, TRUE, 8),
('Harry Potter e a Pedra Filosofal', 'Jane Austen', 'Drama', 1956, TRUE, 9),
('O Senhor dos Anéis', 'John Green', 'Aventura', 1961, FALSE, 10),
('As Crônicas de Nárnia', 'Franz Kafka', 'Terror', 1913, FALSE, 11),
('A Revolução dos Bichos', 'William Golding', 'Romance', 1988, TRUE, 12),
('O Lobo da Estepe', 'Carlos Ruiz Zafón', 'Realismo Mágico', 1947, TRUE, 13),
('O Apanhador no Campo de Centeio', 'Ray Bradbury', 'Ficção', 1943, TRUE, 14),
('A Metamorfose', 'Dan Brown', 'Realismo Mágico', 1991, FALSE, 15),
('O Processo', 'Ernest Hemingway', 'Biografia', 1913, FALSE, 1),
('O Código Da Vinci', 'Jane Austen', 'Biografia', 2003, TRUE, 2),
('Anjos e Demônios', 'J.R.R. Tolkien', 'Infanto-Juvenil', 1953, TRUE, 3),
('Inferno', 'Ernest Hemingway', 'Terror', 2016, TRUE, 4),
('O Símbolo Perdido', 'Ernest Hemingway', 'Drama', 2003, FALSE, 5),
('O Hobbit', 'Stephen King', 'Biografia', 2012, FALSE, 6),
('A Menina que Roubava Livros', 'Paulo Coelho', 'Realismo Mágico', 1989, FALSE, 7),
('It: A Coisa', 'George Orwell', 'Ficção Científica', 1951, TRUE, 8),
('O Iluminado', 'John Green', 'Romance', 1934, TRUE, 9),
('Misery', 'Carlos Ruiz Zafón', 'Terror', 1979, TRUE, 10),
('O Chamado Selvagem', 'Aldous Huxley', 'Romance', 2014, TRUE, 11),
('O Velho e o Mar', 'Ernest Hemingway', 'Fantasia', 1962, TRUE, 12),
('Admirável Mundo Novo', 'Dan Brown', 'Fantasia', 1971, TRUE, 13),
('Neuromancer', 'Paulo Coelho', 'Fantasia', 1959, TRUE, 14),
('Fundação', 'Stephen King', 'Realismo Mágico', 2013, TRUE, 15),
('Duna', 'Dan Brown', 'Ficção Científica', 1920, TRUE, 1),
('Solaris', 'Antoine de Saint-Exupéry', 'Ficção Científica', 1973, TRUE, 2),
('Eu, Robô', 'John Green', 'Fantasia', 1982, TRUE, 3),
('Fahrenheit 451', 'George Orwell', 'Infanto-Juvenil', 1988, TRUE, 4),
('O Mundo de Sofia', 'William Golding', 'Drama', 1963, TRUE, 5),
('O Nome do Vento', 'Patrick Rothfuss', 'Aventura', 1951, TRUE, 6),
('O Temor do Sábio', 'Aldous Huxley', 'Aventura', 2021, TRUE, 7),
('A Sombra do Vento', 'George Orwell', 'Aventura', 2016, FALSE, 8),
('O Jogo do Anjo', 'John Green', 'Ficção', 1957, FALSE, 9),
('Marina', 'Nicholas Sparks', 'Biografia', 1959, FALSE, 10),
('Veronika Decide Morrer', 'Markus Zusak', 'Drama', 1943, TRUE, 11),
('Brida', 'Paulo Coelho', 'Ficção Científica', 1977, TRUE, 12),
('Onze Minutos', 'Dan Brown', 'Ficção', 2019, FALSE, 13),
('A Casa dos Espíritos', 'Markus Zusak', 'Fantasia', 1958, TRUE, 14),
('Eva Luna', 'C.S. Lewis', 'Realismo Mágico', 1902, TRUE, 15),
('O Amor nos Tempos do Cólera', 'Isabel Allende', 'Biografia', 1996, FALSE, 1),
('A Ilha Sob o Mar', 'Ray Bradbury', 'Ficção', 1903, FALSE, 2),
('O Diário de Anne Frank', 'Gabriel García Márquez', 'Ficção', 1916, TRUE, 3),
('A Cabana', 'Isabel Allende', 'Romance', 1936, TRUE, 4),
('Querido John', 'John Green', 'Terror', 1977, TRUE, 5);